/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsSinglePostResponse {
    #[serde(rename = "postId", skip_serializing_if = "Option::is_none")]
    pub post_id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "scheduledFor", skip_serializing_if = "Option::is_none")]
    pub scheduled_for: Option<String>,
    #[serde(rename = "publishedAt", skip_serializing_if = "Option::is_none")]
    pub published_at: Option<String>,
    #[serde(rename = "analytics", skip_serializing_if = "Option::is_none")]
    pub analytics: Option<Box<models::PostAnalytics>>,
    #[serde(rename = "platformAnalytics", skip_serializing_if = "Option::is_none")]
    pub platform_analytics: Option<Vec<models::PlatformAnalytics>>,
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
    #[serde(rename = "platformPostUrl", skip_serializing_if = "Option::is_none")]
    pub platform_post_url: Option<String>,
    #[serde(rename = "isExternal", skip_serializing_if = "Option::is_none")]
    pub is_external: Option<bool>,
}

impl AnalyticsSinglePostResponse {
    pub fn new() -> AnalyticsSinglePostResponse {
        AnalyticsSinglePostResponse {
            post_id: None,
            status: None,
            content: None,
            scheduled_for: None,
            published_at: None,
            analytics: None,
            platform_analytics: None,
            platform: None,
            platform_post_url: None,
            is_external: None,
        }
    }
}
