/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsOverview {
    #[serde(rename = "totalPosts", skip_serializing_if = "Option::is_none")]
    pub total_posts: Option<i32>,
    #[serde(rename = "publishedPosts", skip_serializing_if = "Option::is_none")]
    pub published_posts: Option<i32>,
    #[serde(rename = "scheduledPosts", skip_serializing_if = "Option::is_none")]
    pub scheduled_posts: Option<i32>,
    #[serde(rename = "lastSync", skip_serializing_if = "Option::is_none")]
    pub last_sync: Option<String>,
}

impl AnalyticsOverview {
    pub fn new() -> AnalyticsOverview {
        AnalyticsOverview {
            total_posts: None,
            published_posts: None,
            scheduled_posts: None,
            last_sync: None,
        }
    }
}
