/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsOverviewDataStaleness {
    /// Number of accounts with stale analytics data
    #[serde(rename = "staleAccountCount", skip_serializing_if = "Option::is_none")]
    pub stale_account_count: Option<i32>,
    /// Whether a background sync was triggered for stale accounts
    #[serde(rename = "syncTriggered", skip_serializing_if = "Option::is_none")]
    pub sync_triggered: Option<bool>,
}

impl AnalyticsOverviewDataStaleness {
    pub fn new() -> AnalyticsOverviewDataStaleness {
        AnalyticsOverviewDataStaleness {
            stale_account_count: None,
            sync_triggered: None,
        }
    }
}
