/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BlueskyPlatformData : Bluesky post settings: - Supports text posts with up to 4 images per post - Videos supported (single video per post) - threadItems creates a reply chain (Bluesky thread) - Images exceeding Bluesky's 1MB limit are automatically compressed - Alt text for images is supported via mediaItem properties
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlueskyPlatformData {
    /// Sequence of posts in a Bluesky thread (root then replies in order).
    #[serde(rename = "threadItems", skip_serializing_if = "Option::is_none")]
    pub thread_items: Option<Vec<models::TwitterPlatformDataThreadItemsInner>>,
}

impl BlueskyPlatformData {
    /// Bluesky post settings: - Supports text posts with up to 4 images per post - Videos supported (single video per post) - threadItems creates a reply chain (Bluesky thread) - Images exceeding Bluesky's 1MB limit are automatically compressed - Alt text for images is supported via mediaItem properties
    pub fn new() -> BlueskyPlatformData {
        BlueskyPlatformData { thread_items: None }
    }
}
