/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkUploadPosts200ResponseErrorsInner {
    #[serde(rename = "row", skip_serializing_if = "Option::is_none")]
    pub row: Option<i32>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl BulkUploadPosts200ResponseErrorsInner {
    pub fn new() -> BulkUploadPosts200ResponseErrorsInner {
        BulkUploadPosts200ResponseErrorsInner {
            row: None,
            error: None,
        }
    }
}
