/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateBroadcastRequestTemplate : WhatsApp template (required when platform is whatsapp)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBroadcastRequestTemplate {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(rename = "components", skip_serializing_if = "Option::is_none")]
    pub components: Option<Vec<serde_json::Value>>,
}

impl CreateBroadcastRequestTemplate {
    /// WhatsApp template (required when platform is whatsapp)
    pub fn new() -> CreateBroadcastRequestTemplate {
        CreateBroadcastRequestTemplate {
            name: None,
            language: None,
            components: None,
        }
    }
}
