/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePostRequest {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Post caption/text content. Optional when media is attached (images, videos, etc.). Required for text-only posts. Can also be omitted if all platforms have customContent set.
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "mediaItems", skip_serializing_if = "Option::is_none")]
    pub media_items: Option<Vec<models::CreatePostRequestMediaItemsInner>>,
    #[serde(rename = "platforms", skip_serializing_if = "Option::is_none")]
    pub platforms: Option<Vec<models::CreatePostRequestPlatformsInner>>,
    #[serde(rename = "scheduledFor", skip_serializing_if = "Option::is_none")]
    pub scheduled_for: Option<String>,
    #[serde(rename = "publishNow", skip_serializing_if = "Option::is_none")]
    pub publish_now: Option<bool>,
    #[serde(rename = "isDraft", skip_serializing_if = "Option::is_none")]
    pub is_draft: Option<bool>,
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Tags/keywords for the post. YouTube-specific constraints: - No count limit; duplicates are automatically removed - Each tag must be ≤ 100 characters - Combined total across all tags ≤ 500 characters (YouTube's limit)
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "hashtags", skip_serializing_if = "Option::is_none")]
    pub hashtags: Option<Vec<String>>,
    #[serde(rename = "mentions", skip_serializing_if = "Option::is_none")]
    pub mentions: Option<Vec<String>>,
    #[serde(
        rename = "crosspostingEnabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub crossposting_enabled: Option<bool>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Root-level TikTok settings applied to all TikTok platforms in the request. This is a convenience shorthand. Settings here are merged into each TikTok platform's platformSpecificData, with platform-specific settings taking precedence.
    #[serde(rename = "tiktokSettings", skip_serializing_if = "Option::is_none")]
    pub tiktok_settings: Option<Box<models::TikTokPlatformData>>,
    /// Profile ID to schedule via queue.  When provided (without `scheduledFor`), the post will be automatically assigned to the next available slot from the profile's queue. The system uses distributed locking to prevent race conditions when multiple posts are scheduled concurrently. Do not call `/v1/queue/next-slot` and then use that time in `scheduledFor`. That bypasses the queue system and can cause duplicate slot assignments.
    #[serde(rename = "queuedFromProfile", skip_serializing_if = "Option::is_none")]
    pub queued_from_profile: Option<String>,
    /// Specific queue ID to use when scheduling via queue. Only used when queuedFromProfile is also provided. If omitted, uses the profile's default queue.
    #[serde(rename = "queueId", skip_serializing_if = "Option::is_none")]
    pub queue_id: Option<String>,
}

impl CreatePostRequest {
    pub fn new() -> CreatePostRequest {
        CreatePostRequest {
            title: None,
            content: None,
            media_items: None,
            platforms: None,
            scheduled_for: None,
            publish_now: None,
            is_draft: None,
            timezone: None,
            tags: None,
            hashtags: None,
            mentions: None,
            crossposting_enabled: None,
            metadata: None,
            tiktok_settings: None,
            queued_from_profile: None,
            queue_id: None,
        }
    }
}
