/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteInboxReviewReplyRequest {
    #[serde(rename = "accountId")]
    pub account_id: String,
}

impl DeleteInboxReviewReplyRequest {
    pub fn new(account_id: String) -> DeleteInboxReviewReplyRequest {
        DeleteInboxReviewReplyRequest { account_id }
    }
}
