/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadTikTokVideo200ResponseFormatsInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "ext", skip_serializing_if = "Option::is_none")]
    pub ext: Option<String>,
}

impl DownloadTikTokVideo200ResponseFormatsInner {
    pub fn new() -> DownloadTikTokVideo200ResponseFormatsInner {
        DownloadTikTokVideo200ResponseFormatsInner {
            id: None,
            label: None,
            ext: None,
        }
    }
}
