/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FoodMenuSection {
    #[serde(rename = "labels")]
    pub labels: Vec<models::FoodMenuLabel>,
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::FoodMenuItem>>,
}

impl FoodMenuSection {
    pub fn new(labels: Vec<models::FoodMenuLabel>) -> FoodMenuSection {
        FoodMenuSection {
            labels,
            items: None,
        }
    }
}
