/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FoodMenuLabel {
    /// Display name of the item/section/menu
    #[serde(rename = "displayName")]
    pub display_name: String,
    /// Optional description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// BCP-47 language code (e.g. en, es)
    #[serde(rename = "languageCode", skip_serializing_if = "Option::is_none")]
    pub language_code: Option<String>,
}

impl FoodMenuLabel {
    pub fn new(display_name: String) -> FoodMenuLabel {
        FoodMenuLabel {
            display_name,
            description: None,
            language_code: None,
        }
    }
}
