/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FoodMenuItemOptionsInner {
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<models::FoodMenuLabel>>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<models::FoodMenuItemAttributes>>,
}

impl FoodMenuItemOptionsInner {
    pub fn new() -> FoodMenuItemOptionsInner {
        FoodMenuItemOptionsInner {
            labels: None,
            attributes: None,
        }
    }
}
