/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FoodMenu {
    #[serde(rename = "labels")]
    pub labels: Vec<models::FoodMenuLabel>,
    #[serde(rename = "sections", skip_serializing_if = "Option::is_none")]
    pub sections: Option<Vec<models::FoodMenuSection>>,
    /// Cuisine types (e.g. AMERICAN, ITALIAN, JAPANESE)
    #[serde(rename = "cuisines", skip_serializing_if = "Option::is_none")]
    pub cuisines: Option<Vec<String>>,
    /// URL of the original menu source
    #[serde(rename = "sourceUrl", skip_serializing_if = "Option::is_none")]
    pub source_url: Option<String>,
}

impl FoodMenu {
    pub fn new(labels: Vec<models::FoodMenuLabel>) -> FoodMenu {
        FoodMenu {
            labels,
            sections: None,
            cuisines: None,
            source_url: None,
        }
    }
}
