/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGoogleBusinessLocationDetails200ResponseSpecialHours {
    #[serde(rename = "specialHourPeriods", skip_serializing_if = "Option::is_none")]
    pub special_hour_periods: Option<
        Vec<models::GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner>,
    >,
}

impl GetGoogleBusinessLocationDetails200ResponseSpecialHours {
    pub fn new() -> GetGoogleBusinessLocationDetails200ResponseSpecialHours {
        GetGoogleBusinessLocationDetails200ResponseSpecialHours {
            special_hour_periods: None,
        }
    }
}
