/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetGoogleBusinessLocationDetails200ResponseCategories : Business categories (returned when readMask includes 'categories')
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGoogleBusinessLocationDetails200ResponseCategories {
    #[serde(rename = "primaryCategory", skip_serializing_if = "Option::is_none")]
    pub primary_category:
        Option<Box<models::GetGoogleBusinessLocationDetails200ResponseCategoriesPrimaryCategory>>,
    #[serde(
        rename = "additionalCategories",
        skip_serializing_if = "Option::is_none"
    )]
    pub additional_categories: Option<
        Vec<models::GetGoogleBusinessLocationDetails200ResponseCategoriesAdditionalCategoriesInner>,
    >,
}

impl GetGoogleBusinessLocationDetails200ResponseCategories {
    /// Business categories (returned when readMask includes 'categories')
    pub fn new() -> GetGoogleBusinessLocationDetails200ResponseCategories {
        GetGoogleBusinessLocationDetails200ResponseCategories {
            primary_category: None,
            additional_categories: None,
        }
    }
}
