/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFacebookPages200Response {
    #[serde(rename = "pages", skip_serializing_if = "Option::is_none")]
    pub pages: Option<Vec<models::GetFacebookPages200ResponsePagesInner>>,
    #[serde(rename = "selectedPageId", skip_serializing_if = "Option::is_none")]
    pub selected_page_id: Option<String>,
    #[serde(rename = "cached", skip_serializing_if = "Option::is_none")]
    pub cached: Option<bool>,
}

impl GetFacebookPages200Response {
    pub fn new() -> GetFacebookPages200Response {
        GetFacebookPages200Response {
            pages: None,
            selected_page_id: None,
            cached: None,
        }
    }
}
