/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAnalytics200Response {
    AnalyticsSinglePostResponse(Box<models::AnalyticsSinglePostResponse>),
    AnalyticsListResponse(Box<models::AnalyticsListResponse>),
}

impl Default for GetAnalytics200Response {
    fn default() -> Self {
        Self::AnalyticsSinglePostResponse(Default::default())
    }
}
