/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGoogleBusinessAttributes200ResponseAttributesInnerRepeatedEnumValue {
    #[serde(rename = "setValues", skip_serializing_if = "Option::is_none")]
    pub set_values: Option<Vec<String>>,
    #[serde(rename = "unsetValues", skip_serializing_if = "Option::is_none")]
    pub unset_values: Option<Vec<String>>,
}

impl GetGoogleBusinessAttributes200ResponseAttributesInnerRepeatedEnumValue {
    pub fn new() -> GetGoogleBusinessAttributes200ResponseAttributesInnerRepeatedEnumValue {
        GetGoogleBusinessAttributes200ResponseAttributesInnerRepeatedEnumValue {
            set_values: None,
            unset_values: None,
        }
    }
}
