/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLinkedInAggregateAnalytics200Response {
    LinkedInAggregateAnalyticsTotalResponse(Box<models::LinkedInAggregateAnalyticsTotalResponse>),
    LinkedInAggregateAnalyticsDailyResponse(Box<models::LinkedInAggregateAnalyticsDailyResponse>),
}

impl Default for GetLinkedInAggregateAnalytics200Response {
    fn default() -> Self {
        Self::LinkedInAggregateAnalyticsTotalResponse(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Aggregation {
    #[serde(rename = "DAILY")]
    Daily,
}

impl Default for Aggregation {
    fn default() -> Aggregation {
        Self::Daily
    }
}
