/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetYouTubeTranscript200ResponseSegmentsInner {
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<f64>,
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<f64>,
}

impl GetYouTubeTranscript200ResponseSegmentsInner {
    pub fn new() -> GetYouTubeTranscript200ResponseSegmentsInner {
        GetYouTubeTranscript200ResponseSegmentsInner {
            text: None,
            start: None,
            duration: None,
        }
    }
}
