/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGoogleBusinessLocationDetails200ResponseServiceItemsInnerPrice {
    #[serde(rename = "currencyCode", skip_serializing_if = "Option::is_none")]
    pub currency_code: Option<String>,
    #[serde(rename = "units", skip_serializing_if = "Option::is_none")]
    pub units: Option<String>,
    #[serde(rename = "nanos", skip_serializing_if = "Option::is_none")]
    pub nanos: Option<i32>,
}

impl GetGoogleBusinessLocationDetails200ResponseServiceItemsInnerPrice {
    pub fn new() -> GetGoogleBusinessLocationDetails200ResponseServiceItemsInnerPrice {
        GetGoogleBusinessLocationDetails200ResponseServiceItemsInnerPrice {
            currency_code: None,
            units: None,
            nanos: None,
        }
    }
}
