/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPostReactions200ResponseReactionsInner {
    /// LinkedIn reaction enum (LIKE, PRAISE, EMPATHY, INTEREST, APPRECIATION, ENTERTAINMENT)
    #[serde(rename = "reactionType", skip_serializing_if = "Option::is_none")]
    pub reaction_type: Option<String>,
    /// User-friendly label (Like, Celebrate, Love, Insightful, Support, Funny)
    #[serde(rename = "reactionLabel", skip_serializing_if = "Option::is_none")]
    pub reaction_label: Option<String>,
    #[serde(rename = "reactedAt", skip_serializing_if = "Option::is_none")]
    pub reacted_at: Option<String>,
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<Box<models::GetPostReactions200ResponseReactionsInnerFrom>>,
}

impl GetPostReactions200ResponseReactionsInner {
    pub fn new() -> GetPostReactions200ResponseReactionsInner {
        GetPostReactions200ResponseReactionsInner {
            reaction_type: None,
            reaction_label: None,
            reacted_at: None,
            from: None,
        }
    }
}
