/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBestTimeToPost403Response {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "requiresAddon", skip_serializing_if = "Option::is_none")]
    pub requires_addon: Option<bool>,
}

impl GetBestTimeToPost403Response {
    pub fn new() -> GetBestTimeToPost403Response {
        GetBestTimeToPost403Response {
            error: None,
            requires_addon: None,
        }
    }
}
