/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGoogleBusinessLocationDetails200ResponseCategoriesPrimaryCategory {
    /// Category resource name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Human-readable category name
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
}

impl GetGoogleBusinessLocationDetails200ResponseCategoriesPrimaryCategory {
    pub fn new() -> GetGoogleBusinessLocationDetails200ResponseCategoriesPrimaryCategory {
        GetGoogleBusinessLocationDetails200ResponseCategoriesPrimaryCategory {
            name: None,
            display_name: None,
        }
    }
}
