/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFollowerStats200ResponseStatsValueInner {
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "followers", skip_serializing_if = "Option::is_none")]
    pub followers: Option<f64>,
}

impl GetFollowerStats200ResponseStatsValueInner {
    pub fn new() -> GetFollowerStats200ResponseStatsValueInner {
        GetFollowerStats200ResponseStatsValueInner {
            date: None,
            followers: None,
        }
    }
}
