/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAllAccountsHealth200Response {
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<Box<models::GetAllAccountsHealth200ResponseSummary>>,
    #[serde(rename = "accounts", skip_serializing_if = "Option::is_none")]
    pub accounts: Option<Vec<models::GetAllAccountsHealth200ResponseAccountsInner>>,
}

impl GetAllAccountsHealth200Response {
    pub fn new() -> GetAllAccountsHealth200Response {
        GetAllAccountsHealth200Response {
            summary: None,
            accounts: None,
        }
    }
}
