/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLog200Response {
    #[serde(rename = "log", skip_serializing_if = "Option::is_none")]
    pub log: Option<Box<models::PostLogDetail>>,
}

impl GetLog200Response {
    pub fn new() -> GetLog200Response {
        GetLog200Response { log: None }
    }
}
