/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFacebookPages200ResponsePagesInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "fan_count", skip_serializing_if = "Option::is_none")]
    pub fan_count: Option<i32>,
}

impl GetFacebookPages200ResponsePagesInner {
    pub fn new() -> GetFacebookPages200ResponsePagesInner {
        GetFacebookPages200ResponsePagesInner {
            id: None,
            name: None,
            username: None,
            category: None,
            fan_count: None,
        }
    }
}
