/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFollowerStats200Response {
    #[serde(rename = "accounts", skip_serializing_if = "Option::is_none")]
    pub accounts: Option<Vec<models::AccountWithFollowerStats>>,
    #[serde(rename = "stats", skip_serializing_if = "Option::is_none")]
    pub stats: Option<
        std::collections::HashMap<String, Vec<models::GetFollowerStats200ResponseStatsValueInner>>,
    >,
    #[serde(rename = "dateRange", skip_serializing_if = "Option::is_none")]
    pub date_range: Option<Box<models::GetFollowerStats200ResponseDateRange>>,
    #[serde(rename = "granularity", skip_serializing_if = "Option::is_none")]
    pub granularity: Option<String>,
}

impl GetFollowerStats200Response {
    pub fn new() -> GetFollowerStats200Response {
        GetFollowerStats200Response {
            accounts: None,
            stats: None,
            date_range: None,
            granularity: None,
        }
    }
}
