/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InitiateTelegramConnectRequest {
    /// The Telegram chat ID. Can be: - Numeric ID (e.g., \"-1001234567890\") - Username with @ prefix (e.g., \"@mychannel\")
    #[serde(rename = "chatId")]
    pub chat_id: String,
    /// The profile ID to connect the account to
    #[serde(rename = "profileId")]
    pub profile_id: String,
}

impl InitiateTelegramConnectRequest {
    pub fn new(chat_id: String, profile_id: String) -> InitiateTelegramConnectRequest {
        InitiateTelegramConnectRequest {
            chat_id,
            profile_id,
        }
    }
}
