/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InstagramPlatformData : Constraints: - Feed posts require images with aspect ratio between 0.8 (4:5 portrait) and 1.91 (1.91:1 landscape). - Images outside this range (e.g., 9:16 Stories/TikTok format) must use contentType 'story'. - Validation happens at post creation; invalid images are rejected immediately with helpful error messages. - Carousels support up to 10 media items. - Stories require media; no captions are published with Stories. - User tags: coordinates range from 0.0 to 1.0 representing position from top-left corner. Tagged users receive notifications.  **Automatic Compression (similar to Bluesky):** - All images (story, post, carousel, thumbnails) exceeding 8 MB are automatically compressed using quality reduction and resizing. - Story videos exceeding 100 MB are automatically compressed. - Reel videos exceeding 300 MB are automatically compressed. - Compression uses Sharp (images) and FFmpeg (videos) to maintain quality while meeting size limits. - Original files are preserved; compressed versions are uploaded to blob storage automatically.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstagramPlatformData {
    /// Set to 'story' to publish as a Story. Default posts become Reels or feed depending on media.
    #[serde(rename = "contentType", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<ContentType>,
    /// For Reels only. When true (default), the Reel appears on both the Reels tab and your main profile feed. Set to false to post to the Reels tab only.
    #[serde(rename = "shareToFeed", skip_serializing_if = "Option::is_none")]
    pub share_to_feed: Option<bool>,
    /// Up to 3 Instagram usernames to invite as collaborators (feed/Reels only)
    #[serde(rename = "collaborators", skip_serializing_if = "Option::is_none")]
    pub collaborators: Option<Vec<String>>,
    /// Optional first comment to add after the post is created (not applied to Stories)
    #[serde(rename = "firstComment", skip_serializing_if = "Option::is_none")]
    pub first_comment: Option<String>,
    #[serde(rename = "trialParams", skip_serializing_if = "Option::is_none")]
    pub trial_params: Option<Box<models::InstagramPlatformDataTrialParams>>,
    /// Tag Instagram users in photos by username and position coordinates. Only works for single image posts and the first image of carousel posts. Not supported for stories or videos.
    #[serde(rename = "userTags", skip_serializing_if = "Option::is_none")]
    pub user_tags: Option<Vec<models::InstagramPlatformDataUserTagsInner>>,
    /// Custom name for the original audio in Reels. Replaces the default \"Original Audio\" label. Only applies to Reels (video posts). Can only be set once - either during creation or later from the Instagram audio page in the app.
    #[serde(rename = "audioName", skip_serializing_if = "Option::is_none")]
    pub audio_name: Option<String>,
    /// Millisecond offset from the start of the video to use as the Reel thumbnail. Only applies to Reels (video posts). If a custom thumbnail URL (instagramThumbnail in mediaItems) is provided, it takes priority and this offset is ignored. Defaults to 0 (first frame).
    #[serde(rename = "thumbOffset", skip_serializing_if = "Option::is_none")]
    pub thumb_offset: Option<i32>,
}

impl InstagramPlatformData {
    /// Constraints: - Feed posts require images with aspect ratio between 0.8 (4:5 portrait) and 1.91 (1.91:1 landscape). - Images outside this range (e.g., 9:16 Stories/TikTok format) must use contentType 'story'. - Validation happens at post creation; invalid images are rejected immediately with helpful error messages. - Carousels support up to 10 media items. - Stories require media; no captions are published with Stories. - User tags: coordinates range from 0.0 to 1.0 representing position from top-left corner. Tagged users receive notifications.  **Automatic Compression (similar to Bluesky):** - All images (story, post, carousel, thumbnails) exceeding 8 MB are automatically compressed using quality reduction and resizing. - Story videos exceeding 100 MB are automatically compressed. - Reel videos exceeding 300 MB are automatically compressed. - Compression uses Sharp (images) and FFmpeg (videos) to maintain quality while meeting size limits. - Original files are preserved; compressed versions are uploaded to blob storage automatically.
    pub fn new() -> InstagramPlatformData {
        InstagramPlatformData {
            content_type: None,
            share_to_feed: None,
            collaborators: None,
            first_comment: None,
            trial_params: None,
            user_tags: None,
            audio_name: None,
            thumb_offset: None,
        }
    }
}
/// Set to 'story' to publish as a Story. Default posts become Reels or feed depending on media.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContentType {
    #[serde(rename = "story")]
    Story,
}

impl Default for ContentType {
    fn default() -> ContentType {
        Self::Story
    }
}
