/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InstagramPlatformDataTrialParams : Trial Reels configuration. Trial reels are only shared to non-followers initially. They can later be \"graduated\" (converted to regular reels visible to followers) either manually in the Instagram app or automatically based on performance. Only applies to Reels (video posts).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstagramPlatformDataTrialParams {
    /// The graduation strategy specifies when a trial reel becomes a regular reel: - MANUAL: The trial reel can only be manually graduated from the native Instagram app. - SS_PERFORMANCE: The trial reel will be automatically graduated if it performs well with non-followers.
    #[serde(rename = "graduationStrategy", skip_serializing_if = "Option::is_none")]
    pub graduation_strategy: Option<GraduationStrategy>,
}

impl InstagramPlatformDataTrialParams {
    /// Trial Reels configuration. Trial reels are only shared to non-followers initially. They can later be \"graduated\" (converted to regular reels visible to followers) either manually in the Instagram app or automatically based on performance. Only applies to Reels (video posts).
    pub fn new() -> InstagramPlatformDataTrialParams {
        InstagramPlatformDataTrialParams {
            graduation_strategy: None,
        }
    }
}
/// The graduation strategy specifies when a trial reel becomes a regular reel: - MANUAL: The trial reel can only be manually graduated from the native Instagram app. - SS_PERFORMANCE: The trial reel will be automatically graduated if it performs well with non-followers.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GraduationStrategy {
    #[serde(rename = "MANUAL")]
    Manual,
    #[serde(rename = "SS_PERFORMANCE")]
    SsPerformance,
}

impl Default for GraduationStrategy {
    fn default() -> GraduationStrategy {
        Self::Manual
    }
}
