/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkedInPlatformData : Constraints: - Multi-image posts support up to 20 images. - Multi-video posts are not supported. - Single PDF document posts are supported (max 100MB, ~300 pages). Documents cannot be mixed with other media. - Post ID is returned in the x-restli-id response header. - Link previews are automatically generated for URLs when no media is attached (can be disabled with disableLinkPreview). - Use organizationUrn to post to multiple organizations from the same account connection.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkedInPlatformData {
    /// Target LinkedIn Organization URN for multi-organization posting. Format: \"urn:li:organization:123456789\" If omitted, uses the selected/default organization on the connection. Use GET /api/v1/accounts/{id}/linkedin-organizations to list available organizations.
    #[serde(rename = "organizationUrn", skip_serializing_if = "Option::is_none")]
    pub organization_urn: Option<String>,
    /// Optional first comment to add after the post is created
    #[serde(rename = "firstComment", skip_serializing_if = "Option::is_none")]
    pub first_comment: Option<String>,
    /// Set to true to disable automatic link previews for URLs in the post content (default is false)
    #[serde(rename = "disableLinkPreview", skip_serializing_if = "Option::is_none")]
    pub disable_link_preview: Option<bool>,
}

impl LinkedInPlatformData {
    /// Constraints: - Multi-image posts support up to 20 images. - Multi-video posts are not supported. - Single PDF document posts are supported (max 100MB, ~300 pages). Documents cannot be mixed with other media. - Post ID is returned in the x-restli-id response header. - Link previews are automatically generated for URLs when no media is attached (can be disabled with disableLinkPreview). - Use organizationUrn to post to multiple organizations from the same account connection.
    pub fn new() -> LinkedInPlatformData {
        LinkedInPlatformData {
            organization_urn: None,
            first_comment: None,
            disable_link_preview: None,
        }
    }
}
