/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkedInAggregateAnalyticsDailyResponseAnalyticsImpressionsInner {
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
}

impl LinkedInAggregateAnalyticsDailyResponseAnalyticsImpressionsInner {
    pub fn new() -> LinkedInAggregateAnalyticsDailyResponseAnalyticsImpressionsInner {
        LinkedInAggregateAnalyticsDailyResponseAnalyticsImpressionsInner {
            date: None,
            count: None,
        }
    }
}
