/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListPinterestBoardsForSelection200Response {
    #[serde(rename = "boards", skip_serializing_if = "Option::is_none")]
    pub boards: Option<Vec<models::ListPinterestBoardsForSelection200ResponseBoardsInner>>,
}

impl ListPinterestBoardsForSelection200Response {
    pub fn new() -> ListPinterestBoardsForSelection200Response {
        ListPinterestBoardsForSelection200Response { boards: None }
    }
}
