/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListLinkedInOrganizations200Response {
    #[serde(rename = "organizations", skip_serializing_if = "Option::is_none")]
    pub organizations: Option<Vec<models::ListLinkedInOrganizations200ResponseOrganizationsInner>>,
}

impl ListLinkedInOrganizations200Response {
    pub fn new() -> ListLinkedInOrganizations200Response {
        ListLinkedInOrganizations200Response {
            organizations: None,
        }
    }
}
