/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListQueueSlots200Response {
    ListQueueSlots200ResponseOneOf(Box<models::ListQueueSlots200ResponseOneOf>),
    ListQueueSlots200ResponseOneOf1(Box<models::ListQueueSlots200ResponseOneOf1>),
}

impl Default for ListQueueSlots200Response {
    fn default() -> Self {
        Self::ListQueueSlots200ResponseOneOf(Default::default())
    }
}
