/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListInboxReviews200ResponseSummary {
    #[serde(rename = "totalReviews", skip_serializing_if = "Option::is_none")]
    pub total_reviews: Option<i32>,
    #[serde(rename = "averageRating", skip_serializing_if = "Option::is_none")]
    pub average_rating: Option<f64>,
}

impl ListInboxReviews200ResponseSummary {
    pub fn new() -> ListInboxReviews200ResponseSummary {
        ListInboxReviews200ResponseSummary {
            total_reviews: None,
            average_rating: None,
        }
    }
}
