/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAccounts200Response {
    #[serde(rename = "accounts", skip_serializing_if = "Option::is_none")]
    pub accounts: Option<Vec<models::SocialAccount>>,
    /// Whether user has analytics add-on access
    #[serde(rename = "hasAnalyticsAccess", skip_serializing_if = "Option::is_none")]
    pub has_analytics_access: Option<bool>,
}

impl ListAccounts200Response {
    pub fn new() -> ListAccounts200Response {
        ListAccounts200Response {
            accounts: None,
            has_analytics_access: None,
        }
    }
}
