/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MediaItem : Media referenced in posts. URLs must be publicly reachable over HTTPS by the destination platforms. When using third‑party storage, ensure signed links remain valid until upload completes.  **Uploading Media:** Use `POST /v1/media/presign` to get a presigned URL, then upload your file directly to cloud storage. Supports files up to 5GB. See the `/v1/media/presign` endpoint documentation for details.  **Automatic Media Compression:** Late automatically compresses media that exceeds platform limits, so you don't need to worry about file size restrictions. Compression happens server-side during publishing.  **Image compression by platform:** - Twitter/X: >5 MB - Instagram: >8 MB - Threads: >8 MB - Facebook: >10 MB - LinkedIn: >8 MB - TikTok: >20 MB - Pinterest: >32 MB - Reddit: >20 MB - Snapchat: >20 MB - Telegram: >10 MB - Bluesky: >1 MB - YouTube (thumbnails): >2 MB - Google Business: >5 MB  **Video compression by platform:** - Twitter/X: >512 MB - Instagram Stories: >100 MB - Instagram Reels: >300 MB - Facebook: >4 GB - LinkedIn: >5 GB - TikTok: >4 GB - Pinterest: >2 GB - Snapchat: >500 MB - Telegram: >50 MB  Note: Videos larger than 200 MB may not be compressed due to server timeout constraints. For best results, compress very large videos before uploading.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaItem {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "filename", skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    /// Optional file size in bytes
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    /// Optional MIME type (e.g. image/jpeg, video/mp4)
    #[serde(rename = "mimeType", skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    /// Optional thumbnail image URL for videos
    #[serde(rename = "thumbnail", skip_serializing_if = "Option::is_none")]
    pub thumbnail: Option<String>,
    /// Optional custom cover image URL for Instagram Reels
    #[serde(rename = "instagramThumbnail", skip_serializing_if = "Option::is_none")]
    pub instagram_thumbnail: Option<String>,
    /// Internal flag indicating the image was resized for TikTok
    #[serde(rename = "tiktokProcessed", skip_serializing_if = "Option::is_none")]
    pub tiktok_processed: Option<bool>,
}

impl MediaItem {
    /// Media referenced in posts. URLs must be publicly reachable over HTTPS by the destination platforms. When using third‑party storage, ensure signed links remain valid until upload completes.  **Uploading Media:** Use `POST /v1/media/presign` to get a presigned URL, then upload your file directly to cloud storage. Supports files up to 5GB. See the `/v1/media/presign` endpoint documentation for details.  **Automatic Media Compression:** Late automatically compresses media that exceeds platform limits, so you don't need to worry about file size restrictions. Compression happens server-side during publishing.  **Image compression by platform:** - Twitter/X: >5 MB - Instagram: >8 MB - Threads: >8 MB - Facebook: >10 MB - LinkedIn: >8 MB - TikTok: >20 MB - Pinterest: >32 MB - Reddit: >20 MB - Snapchat: >20 MB - Telegram: >10 MB - Bluesky: >1 MB - YouTube (thumbnails): >2 MB - Google Business: >5 MB  **Video compression by platform:** - Twitter/X: >512 MB - Instagram Stories: >100 MB - Instagram Reels: >300 MB - Facebook: >4 GB - LinkedIn: >5 GB - TikTok: >4 GB - Pinterest: >2 GB - Snapchat: >500 MB - Telegram: >50 MB  Note: Videos larger than 200 MB may not be compressed due to server timeout constraints. For best results, compress very large videos before uploading.
    pub fn new() -> MediaItem {
        MediaItem {
            r#type: None,
            url: None,
            filename: None,
            size: None,
            mime_type: None,
            thumbnail: None,
            instagram_thumbnail: None,
            tiktok_processed: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "image")]
    Image,
    #[serde(rename = "video")]
    Video,
    #[serde(rename = "gif")]
    Gif,
    #[serde(rename = "document")]
    Document,
}

impl Default for Type {
    fn default() -> Type {
        Self::Image
    }
}
