/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformAnalytics {
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "accountUsername", skip_serializing_if = "Option::is_none")]
    pub account_username: Option<String>,
    #[serde(rename = "analytics", skip_serializing_if = "Option::is_none")]
    pub analytics: Option<Box<models::PostAnalytics>>,
    #[serde(rename = "accountMetrics", skip_serializing_if = "Option::is_none")]
    pub account_metrics: Option<Box<models::PlatformAnalyticsAccountMetrics>>,
}

impl PlatformAnalytics {
    pub fn new() -> PlatformAnalytics {
        PlatformAnalytics {
            platform: None,
            status: None,
            account_id: None,
            account_username: None,
            analytics: None,
            account_metrics: None,
        }
    }
}
