/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformAnalyticsAccountMetrics {
    /// Followers/fans count (e.g., Instagram, Facebook Pages, Twitter)
    #[serde(rename = "followers", skip_serializing_if = "Option::is_none")]
    pub followers: Option<i32>,
    /// Subscribers count (e.g., YouTube)
    #[serde(rename = "subscribers", skip_serializing_if = "Option::is_none")]
    pub subscribers: Option<i32>,
    #[serde(rename = "lastUpdated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
}

impl PlatformAnalyticsAccountMetrics {
    pub fn new() -> PlatformAnalyticsAccountMetrics {
        PlatformAnalyticsAccountMetrics {
            followers: None,
            subscribers: None,
            last_updated: None,
        }
    }
}
