/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostLogDetailAllOfAccountId : Populated account reference
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostLogDetailAllOfAccountId {
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub _id: Option<String>,
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
}

impl PostLogDetailAllOfAccountId {
    /// Populated account reference
    pub fn new() -> PostLogDetailAllOfAccountId {
        PostLogDetailAllOfAccountId {
            _id: None,
            platform: None,
            username: None,
            display_name: None,
        }
    }
}
