/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostLogDetailAllOfPostId : Populated post with full details
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostLogDetailAllOfPostId {
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub _id: Option<String>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "scheduledFor", skip_serializing_if = "Option::is_none")]
    pub scheduled_for: Option<String>,
    #[serde(rename = "platforms", skip_serializing_if = "Option::is_none")]
    pub platforms: Option<Vec<serde_json::Value>>,
    #[serde(rename = "mediaItems", skip_serializing_if = "Option::is_none")]
    pub media_items: Option<Vec<serde_json::Value>>,
}

impl PostLogDetailAllOfPostId {
    /// Populated post with full details
    pub fn new() -> PostLogDetailAllOfPostId {
        PostLogDetailAllOfPostId {
            _id: None,
            content: None,
            status: None,
            scheduled_for: None,
            platforms: None,
            media_items: None,
        }
    }
}
