/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueueNextSlotResponse {
    #[serde(rename = "profileId", skip_serializing_if = "Option::is_none")]
    pub profile_id: Option<String>,
    #[serde(rename = "nextSlot", skip_serializing_if = "Option::is_none")]
    pub next_slot: Option<String>,
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
}

impl QueueNextSlotResponse {
    pub fn new() -> QueueNextSlotResponse {
        QueueNextSlotResponse {
            profile_id: None,
            next_slot: None,
            timezone: None,
        }
    }
}
