/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplyToInboxPostRequest {
    #[serde(rename = "accountId")]
    pub account_id: String,
    #[serde(rename = "message")]
    pub message: String,
    /// Reply to specific comment (optional)
    #[serde(rename = "commentId", skip_serializing_if = "Option::is_none")]
    pub comment_id: Option<String>,
    /// (Reddit only) Subreddit name for replies
    #[serde(rename = "subreddit", skip_serializing_if = "Option::is_none")]
    pub subreddit: Option<String>,
    /// (Bluesky only) Parent content identifier
    #[serde(rename = "parentCid", skip_serializing_if = "Option::is_none")]
    pub parent_cid: Option<String>,
    /// (Bluesky only) Root post URI
    #[serde(rename = "rootUri", skip_serializing_if = "Option::is_none")]
    pub root_uri: Option<String>,
    /// (Bluesky only) Root post CID
    #[serde(rename = "rootCid", skip_serializing_if = "Option::is_none")]
    pub root_cid: Option<String>,
}

impl ReplyToInboxPostRequest {
    pub fn new(account_id: String, message: String) -> ReplyToInboxPostRequest {
        ReplyToInboxPostRequest {
            account_id,
            message,
            comment_id: None,
            subreddit: None,
            parent_cid: None,
            root_uri: None,
            root_cid: None,
        }
    }
}
