/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplyToInboxPost200ResponseData {
    #[serde(rename = "commentId", skip_serializing_if = "Option::is_none")]
    pub comment_id: Option<String>,
    #[serde(rename = "isReply", skip_serializing_if = "Option::is_none")]
    pub is_reply: Option<bool>,
    /// Bluesky CID
    #[serde(rename = "cid", skip_serializing_if = "Option::is_none")]
    pub cid: Option<String>,
}

impl ReplyToInboxPost200ResponseData {
    pub fn new() -> ReplyToInboxPost200ResponseData {
        ReplyToInboxPost200ResponseData {
            comment_id: None,
            is_reply: None,
            cid: None,
        }
    }
}
