/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SelectGoogleBusinessLocationRequestUserProfile : Decoded user profile object from the OAuth callback. **Important:** This contains  the refresh token needed for token refresh. Always include this field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelectGoogleBusinessLocationRequestUserProfile {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Google refresh token for long-lived access
    #[serde(rename = "refreshToken", skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<String>,
    /// Token expiration time in seconds
    #[serde(rename = "tokenExpiresIn", skip_serializing_if = "Option::is_none")]
    pub token_expires_in: Option<i32>,
    /// Granted OAuth scopes
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
}

impl SelectGoogleBusinessLocationRequestUserProfile {
    /// Decoded user profile object from the OAuth callback. **Important:** This contains  the refresh token needed for token refresh. Always include this field.
    pub fn new() -> SelectGoogleBusinessLocationRequestUserProfile {
        SelectGoogleBusinessLocationRequestUserProfile {
            id: None,
            name: None,
            refresh_token: None,
            token_expires_in: None,
            scope: None,
        }
    }
}
