/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SelectFacebookPageRequestUserProfile : Decoded user profile object from the OAuth callback
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelectFacebookPageRequestUserProfile {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "profilePicture", skip_serializing_if = "Option::is_none")]
    pub profile_picture: Option<String>,
}

impl SelectFacebookPageRequestUserProfile {
    /// Decoded user profile object from the OAuth callback
    pub fn new() -> SelectFacebookPageRequestUserProfile {
        SelectFacebookPageRequestUserProfile {
            id: None,
            name: None,
            profile_picture: None,
        }
    }
}
