/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendPrivateReplyToCommentRequest {
    /// The Instagram social account ID
    #[serde(rename = "accountId")]
    pub account_id: String,
    /// The message text to send as a private DM
    #[serde(rename = "message")]
    pub message: String,
}

impl SendPrivateReplyToCommentRequest {
    pub fn new(account_id: String, message: String) -> SendPrivateReplyToCommentRequest {
        SendPrivateReplyToCommentRequest {
            account_id,
            message,
        }
    }
}
