/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendInboxMessageRequestQuickRepliesInner {
    /// Button label (max 20 chars)
    #[serde(rename = "title")]
    pub title: String,
    /// Payload sent back on tap
    #[serde(rename = "payload")]
    pub payload: String,
    /// Optional icon URL (Meta only)
    #[serde(rename = "imageUrl", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
}

impl SendInboxMessageRequestQuickRepliesInner {
    pub fn new(title: String, payload: String) -> SendInboxMessageRequestQuickRepliesInner {
        SendInboxMessageRequestQuickRepliesInner {
            title,
            payload,
            image_url: None,
        }
    }
}
