/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendInboxMessageRequest {
    /// Social account ID
    #[serde(rename = "accountId")]
    pub account_id: String,
    /// Message text
    #[serde(rename = "message")]
    pub message: String,
}

impl SendInboxMessageRequest {
    pub fn new(account_id: String, message: String) -> SendInboxMessageRequest {
        SendInboxMessageRequest {
            account_id,
            message,
        }
    }
}
