/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetTelegramCommandsRequestCommandsInner {
    /// Bot command without leading slash
    #[serde(rename = "command")]
    pub command: String,
    /// Command description
    #[serde(rename = "description")]
    pub description: String,
}

impl SetTelegramCommandsRequestCommandsInner {
    pub fn new(command: String, description: String) -> SetTelegramCommandsRequestCommandsInner {
        SetTelegramCommandsRequestCommandsInner {
            command,
            description,
        }
    }
}
