/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SnapchatPlatformData : Snapchat Public Profile API constraints:  **General Requirements:** - Snapchat requires a Public Profile to publish content - Media is required for all content types (no text-only posts) - Only one media item per post is supported - Media is automatically encrypted using AES-256-CBC before upload  **Content Types:** - **Story** (default): Ephemeral content visible for 24 hours. No caption/text supported. - **Saved Story**: Permanent story on your Public Profile. Uses post content as title (max 45 chars). - **Spotlight**: Video content for Snapchat's entertainment feed. Supports description (max 160 chars) with hashtags.  **Media Constraints:** - Images: max 20 MB, JPEG/PNG format - Videos: max 500 MB, MP4 format, 5-60 seconds duration, minimum 540x960px resolution - Aspect ratio: 9:16 recommended  **Analytics:** - Views, screenshots, shares, unique viewers, completion rate available - Analytics are fetched per content type (story/saved_story/spotlight)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SnapchatPlatformData {
    /// Type of Snapchat content to publish: - `story` - Ephemeral snap visible for 24 hours (default) - `saved_story` - Permanent story saved to Public Profile - `spotlight` - Video posted to Spotlight (Snapchat's TikTok-like feed)
    #[serde(rename = "contentType", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<ContentType>,
}

impl SnapchatPlatformData {
    /// Snapchat Public Profile API constraints:  **General Requirements:** - Snapchat requires a Public Profile to publish content - Media is required for all content types (no text-only posts) - Only one media item per post is supported - Media is automatically encrypted using AES-256-CBC before upload  **Content Types:** - **Story** (default): Ephemeral content visible for 24 hours. No caption/text supported. - **Saved Story**: Permanent story on your Public Profile. Uses post content as title (max 45 chars). - **Spotlight**: Video content for Snapchat's entertainment feed. Supports description (max 160 chars) with hashtags.  **Media Constraints:** - Images: max 20 MB, JPEG/PNG format - Videos: max 500 MB, MP4 format, 5-60 seconds duration, minimum 540x960px resolution - Aspect ratio: 9:16 recommended  **Analytics:** - Views, screenshots, shares, unique viewers, completion rate available - Analytics are fetched per content type (story/saved_story/spotlight)
    pub fn new() -> SnapchatPlatformData {
        SnapchatPlatformData { content_type: None }
    }
}
/// Type of Snapchat content to publish: - `story` - Ephemeral snap visible for 24 hours (default) - `saved_story` - Permanent story saved to Public Profile - `spotlight` - Video posted to Spotlight (Snapchat's TikTok-like feed)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContentType {
    #[serde(rename = "story")]
    Story,
    #[serde(rename = "saved_story")]
    SavedStory,
    #[serde(rename = "spotlight")]
    Spotlight,
}

impl Default for ContentType {
    fn default() -> ContentType {
        Self::Story
    }
}
