/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ThreadsPlatformData : Constraints: - Carousel posts support up to 10 images (no videos in carousels). - Single posts support one image or one video. - Videos must be H.264/AAC MP4 format, max 5 minutes duration. - Images must be JPEG or PNG, max 8 MB each. - threadItems creates a reply chain (Threads equivalent of Twitter threads).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThreadsPlatformData {
    /// Sequence of posts in a Threads thread (root then replies in order).
    #[serde(rename = "threadItems", skip_serializing_if = "Option::is_none")]
    pub thread_items: Option<Vec<models::TwitterPlatformDataThreadItemsInner>>,
}

impl ThreadsPlatformData {
    /// Constraints: - Carousel posts support up to 10 images (no videos in carousels). - Single posts support one image or one video. - Videos must be H.264/AAC MP4 format, max 5 minutes duration. - Images must be JPEG or PNG, max 8 MB each. - threadItems creates a reply chain (Threads equivalent of Twitter threads).
    pub fn new() -> ThreadsPlatformData {
        ThreadsPlatformData { thread_items: None }
    }
}
