/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateGoogleBusinessLocationDetailsRequestCategories : Primary and additional business categories. Use updateMask='categories' to update.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateGoogleBusinessLocationDetailsRequestCategories {
    #[serde(rename = "primaryCategory", skip_serializing_if = "Option::is_none")]
    pub primary_category:
        Option<Box<models::UpdateGoogleBusinessLocationDetailsRequestCategoriesPrimaryCategory>>,
    #[serde(
        rename = "additionalCategories",
        skip_serializing_if = "Option::is_none"
    )]
    pub additional_categories: Option<
        Vec<models::UpdateGoogleBusinessLocationDetailsRequestCategoriesAdditionalCategoriesInner>,
    >,
}

impl UpdateGoogleBusinessLocationDetailsRequestCategories {
    /// Primary and additional business categories. Use updateMask='categories' to update.
    pub fn new() -> UpdateGoogleBusinessLocationDetailsRequestCategories {
        UpdateGoogleBusinessLocationDetailsRequestCategories {
            primary_category: None,
            additional_categories: None,
        }
    }
}
