/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateGoogleBusinessLocationDetailsRequest {
    /// Required. Comma-separated fields to update (e.g. 'regularHours', 'specialHours', 'profile.description')
    #[serde(rename = "updateMask")]
    pub update_mask: String,
    #[serde(rename = "regularHours", skip_serializing_if = "Option::is_none")]
    pub regular_hours: Option<Box<models::UpdateGoogleBusinessLocationDetailsRequestRegularHours>>,
    #[serde(rename = "specialHours", skip_serializing_if = "Option::is_none")]
    pub special_hours: Option<Box<models::GetGoogleBusinessLocationDetails200ResponseSpecialHours>>,
    #[serde(rename = "profile", skip_serializing_if = "Option::is_none")]
    pub profile: Option<Box<models::UpdateGoogleBusinessLocationDetailsRequestProfile>>,
    #[serde(rename = "websiteUri", skip_serializing_if = "Option::is_none")]
    pub website_uri: Option<String>,
    #[serde(rename = "phoneNumbers", skip_serializing_if = "Option::is_none")]
    pub phone_numbers: Option<Box<models::GetGoogleBusinessLocationDetails200ResponsePhoneNumbers>>,
}

impl UpdateGoogleBusinessLocationDetailsRequest {
    pub fn new(update_mask: String) -> UpdateGoogleBusinessLocationDetailsRequest {
        UpdateGoogleBusinessLocationDetailsRequest {
            update_mask,
            regular_hours: None,
            special_hours: None,
            profile: None,
            website_uri: None,
            phone_numbers: None,
        }
    }
}
