/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateInboxConversationRequest {
    /// Social account ID
    #[serde(rename = "accountId")]
    pub account_id: String,
    #[serde(rename = "status")]
    pub status: Status,
}

impl UpdateInboxConversationRequest {
    pub fn new(account_id: String, status: Status) -> UpdateInboxConversationRequest {
        UpdateInboxConversationRequest { account_id, status }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "archived")]
    Archived,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}
