/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateGoogleBusinessAttributesRequestAttributesInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<serde_json::Value>>,
    #[serde(rename = "repeatedEnumValue", skip_serializing_if = "Option::is_none")]
    pub repeated_enum_value:
        Option<Box<models::GetGoogleBusinessAttributes200ResponseAttributesInnerRepeatedEnumValue>>,
}

impl UpdateGoogleBusinessAttributesRequestAttributesInner {
    pub fn new() -> UpdateGoogleBusinessAttributesRequestAttributesInner {
        UpdateGoogleBusinessAttributesRequestAttributesInner {
            name: None,
            values: None,
            repeated_enum_value: None,
        }
    }
}
