/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRedditSubredditsRequest {
    #[serde(rename = "defaultSubreddit")]
    pub default_subreddit: String,
}

impl UpdateRedditSubredditsRequest {
    pub fn new(default_subreddit: String) -> UpdateRedditSubredditsRequest {
        UpdateRedditSubredditsRequest { default_subreddit }
    }
}
