/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePostRequest {
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "scheduledFor", skip_serializing_if = "Option::is_none")]
    pub scheduled_for: Option<String>,
    /// Root-level TikTok settings applied to all TikTok platforms in the request. This is a convenience shorthand. Settings here are merged into each TikTok platform's platformSpecificData, with platform-specific settings taking precedence.
    #[serde(rename = "tiktokSettings", skip_serializing_if = "Option::is_none")]
    pub tiktok_settings: Option<Box<models::TikTokPlatformData>>,
}

impl UpdatePostRequest {
    pub fn new() -> UpdatePostRequest {
        UpdatePostRequest {
            content: None,
            scheduled_for: None,
            tiktok_settings: None,
        }
    }
}
