/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateQueueSlot200Response {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<Box<models::QueueSchedule>>,
    #[serde(rename = "nextSlots", skip_serializing_if = "Option::is_none")]
    pub next_slots: Option<Vec<String>>,
    #[serde(rename = "reshuffledCount", skip_serializing_if = "Option::is_none")]
    pub reshuffled_count: Option<i32>,
}

impl UpdateQueueSlot200Response {
    pub fn new() -> UpdateQueueSlot200Response {
        UpdateQueueSlot200Response {
            success: None,
            schedule: None,
            next_slots: None,
            reshuffled_count: None,
        }
    }
}
