/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateFacebookPageRequest {
    #[serde(rename = "selectedPageId")]
    pub selected_page_id: String,
}

impl UpdateFacebookPageRequest {
    pub fn new(selected_page_id: String) -> UpdateFacebookPageRequest {
        UpdateFacebookPageRequest { selected_page_id }
    }
}
