/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ValidatePost200ResponseOneOf : Valid post
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidatePost200ResponseOneOf {
    #[serde(rename = "valid", skip_serializing_if = "Option::is_none")]
    pub valid: Option<Valid>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "warnings", skip_serializing_if = "Option::is_none")]
    pub warnings: Option<Vec<models::ValidatePost200ResponseOneOfWarningsInner>>,
}

impl ValidatePost200ResponseOneOf {
    /// Valid post
    pub fn new() -> ValidatePost200ResponseOneOf {
        ValidatePost200ResponseOneOf {
            valid: None,
            message: None,
            warnings: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Valid {
    #[serde(rename = "true")]
    True,
}

impl Default for Valid {
    fn default() -> Valid {
        Self::True
    }
}
