/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ValidateSubreddit200ResponseOneOf1 : Subreddit not found
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidateSubreddit200ResponseOneOf1 {
    #[serde(rename = "exists", skip_serializing_if = "Option::is_none")]
    pub exists: Option<Exists>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl ValidateSubreddit200ResponseOneOf1 {
    /// Subreddit not found
    pub fn new() -> ValidateSubreddit200ResponseOneOf1 {
        ValidateSubreddit200ResponseOneOf1 {
            exists: None,
            error: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Exists {
    #[serde(rename = "false")]
    False,
}

impl Default for Exists {
    fn default() -> Exists {
        Self::False
    }
}
