/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ValidatePost200ResponseOneOf1 : Invalid post
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidatePost200ResponseOneOf1 {
    #[serde(rename = "valid", skip_serializing_if = "Option::is_none")]
    pub valid: Option<Valid>,
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::ValidatePost200ResponseOneOf1ErrorsInner>>,
    #[serde(rename = "warnings", skip_serializing_if = "Option::is_none")]
    pub warnings: Option<Vec<models::ValidatePost200ResponseOneOfWarningsInner>>,
}

impl ValidatePost200ResponseOneOf1 {
    /// Invalid post
    pub fn new() -> ValidatePost200ResponseOneOf1 {
        ValidatePost200ResponseOneOf1 {
            valid: None,
            errors: None,
            warnings: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Valid {
    #[serde(rename = "false")]
    False,
}

impl Default for Valid {
    fn default() -> Valid {
        Self::False
    }
}
