/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ValidatePost200Response {
    ValidatePost200ResponseOneOf(Box<models::ValidatePost200ResponseOneOf>),
    ValidatePost200ResponseOneOf1(Box<models::ValidatePost200ResponseOneOf1>),
}

impl Default for ValidatePost200Response {
    fn default() -> Self {
        Self::ValidatePost200ResponseOneOf(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Valid {
    #[serde(rename = "false")]
    False,
}

impl Default for Valid {
    fn default() -> Valid {
        Self::False
    }
}
