/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidatePost200ResponseOneOfWarningsInner {
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
    #[serde(rename = "warning", skip_serializing_if = "Option::is_none")]
    pub warning: Option<String>,
}

impl ValidatePost200ResponseOneOfWarningsInner {
    pub fn new() -> ValidatePost200ResponseOneOfWarningsInner {
        ValidatePost200ResponseOneOfWarningsInner {
            platform: None,
            warning: None,
        }
    }
}
