/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ValidateSubreddit200ResponseOneOf : Subreddit exists
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidateSubreddit200ResponseOneOf {
    #[serde(rename = "exists", skip_serializing_if = "Option::is_none")]
    pub exists: Option<bool>,
    #[serde(rename = "subreddit", skip_serializing_if = "Option::is_none")]
    pub subreddit: Option<Box<models::ValidateSubreddit200ResponseOneOfSubreddit>>,
}

impl ValidateSubreddit200ResponseOneOf {
    /// Subreddit exists
    pub fn new() -> ValidateSubreddit200ResponseOneOf {
        ValidateSubreddit200ResponseOneOf {
            exists: None,
            subreddit: None,
        }
    }
}
