/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookPayloadPostPostPlatformsInner {
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "publishedUrl", skip_serializing_if = "Option::is_none")]
    pub published_url: Option<String>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl WebhookPayloadPostPostPlatformsInner {
    pub fn new() -> WebhookPayloadPostPostPlatformsInner {
        WebhookPayloadPostPostPlatformsInner {
            platform: None,
            status: None,
            published_url: None,
            error: None,
        }
    }
}
