/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// YouTubePlatformData : YouTube video upload settings: - Videos ≤ 3 minutes are automatically detected as YouTube Shorts - Videos > 3 minutes become regular YouTube videos - Custom thumbnails supported for regular videos (via mediaItem.thumbnail) - Custom thumbnails NOT supported for Shorts via API - Scheduled videos are uploaded immediately as the specified visibility and published at scheduled time - Visibility defaults to \"public\" if not specified - madeForKids defaults to false (not child-directed) - Set containsSyntheticMedia: true if your video contains AI-generated content
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct YouTubePlatformData {
    /// Video title. Defaults to first line of content or \"Untitled Video\". Must be ≤ 100 characters.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Video visibility setting: - public: Anyone can search for and watch (default) - unlisted: Only people with the link can watch - private: Only you and people you specifically share with can watch
    #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
    pub visibility: Option<Visibility>,
    /// COPPA compliance: Audience designation for the video. - true: Video is made for kids (child-directed content) - false: Video is NOT made for kids (default)  This field maps to YouTube's `selfDeclaredMadeForKids` setting. Videos marked as made for kids have restricted features (no comments, no notifications, limited ad targeting).  IMPORTANT: If not specified, defaults to false. YouTube requires this to be explicitly set, otherwise the video may be blocked from views until configured in YouTube Studio.
    #[serde(rename = "madeForKids", skip_serializing_if = "Option::is_none")]
    pub made_for_kids: Option<bool>,
    /// Optional first comment to post immediately after video upload. Up to 10,000 characters (YouTube's comment limit).
    #[serde(rename = "firstComment", skip_serializing_if = "Option::is_none")]
    pub first_comment: Option<String>,
    /// AI-generated content disclosure flag. Set to true if your video contains AI-generated or synthetic content that could be mistaken for real people, places, or events. This helps viewers understand when realistic content has been created or altered using AI. YouTube may add a label to videos when this is set. Added to YouTube Data API in October 2024.
    #[serde(
        rename = "containsSyntheticMedia",
        skip_serializing_if = "Option::is_none"
    )]
    pub contains_synthetic_media: Option<bool>,
    /// YouTube video category ID. Defaults to '22' (People & Blogs). Common categories: 1 (Film & Animation), 2 (Autos & Vehicles), 10 (Music), 15 (Pets & Animals), 17 (Sports), 20 (Gaming), 22 (People & Blogs), 23 (Comedy), 24 (Entertainment), 25 (News & Politics), 26 (Howto & Style), 27 (Education), 28 (Science & Technology).
    #[serde(rename = "categoryId", skip_serializing_if = "Option::is_none")]
    pub category_id: Option<String>,
}

impl YouTubePlatformData {
    /// YouTube video upload settings: - Videos ≤ 3 minutes are automatically detected as YouTube Shorts - Videos > 3 minutes become regular YouTube videos - Custom thumbnails supported for regular videos (via mediaItem.thumbnail) - Custom thumbnails NOT supported for Shorts via API - Scheduled videos are uploaded immediately as the specified visibility and published at scheduled time - Visibility defaults to \"public\" if not specified - madeForKids defaults to false (not child-directed) - Set containsSyntheticMedia: true if your video contains AI-generated content
    pub fn new() -> YouTubePlatformData {
        YouTubePlatformData {
            title: None,
            visibility: None,
            made_for_kids: None,
            first_comment: None,
            contains_synthetic_media: None,
            category_id: None,
        }
    }
}
/// Video visibility setting: - public: Anyone can search for and watch (default) - unlisted: Only people with the link can watch - private: Only you and people you specifically share with can watch
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Visibility {
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "unlisted")]
    Unlisted,
}

impl Default for Visibility {
    fn default() -> Visibility {
        Self::Public
    }
}
