/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct YouTubeScopeMissingResponse {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "scopeStatus", skip_serializing_if = "Option::is_none")]
    pub scope_status: Option<Box<models::YouTubeScopeMissingResponseScopeStatus>>,
}

impl YouTubeScopeMissingResponse {
    pub fn new() -> YouTubeScopeMissingResponse {
        YouTubeScopeMissingResponse {
            success: None,
            error: None,
            code: None,
            scope_status: None,
        }
    }
}
